### ISSUE TITLE
wrong function

### ISSUE THREAD

**Issue by lolonger** [Attila94/refinenet-keras#2]
I think there is somthing wrong with your ChainedResidualPooling function...
Maybe you can check it again.

**Comment by lolonger** [comment]
just look at line 84-85
net = MaxPooling2D(pool_size = (5,5), strides = 1, padding = 'same')(net_relu)
net = Conv2D(n_filters, 3, padding='same')(net_relu)

**Comment by Attila94** [comment]
Thanks, you're correct. Line 85 should be
`net = Conv2D(n_filters, 3, padding='same')(net)`

You can submit a pull request if you want, or else I'll make a commit sometime later this week.

Edit: Nevermind, all good.

**Comment by Attila94** [comment]
So as it turns out, the correct architecture is having more difficulty converging than the one in which I accidentally skipped the maxpool layers in the chained residual pooling blocks.
I'm now playing around with the updated chained residual pooling block from the original refinenet github to see if that works any better, will post results soon.

**Comment by srihari-humbarwadi** [comment]
I have had trouble training this architecture too

**Comment by Attila94** [comment]
Latest commit should fix all issues.
