### ISSUE TITLE
Structure of images and labels in dataset

### ISSUE THREAD

**Issue by sreesindhu-sabbineni** [Attila94/refinenet-keras#4]
Just want to know the structure of images and labels for each of the training, validation and testing folders in the dataset. I am assuming images folder contains the images whereas the labels folder is a .txt or .csv file containing the class labels of the images. My doubt does the name of the image in images folder should be it's corresponding class label.

**Comment by Attila94** [comment]
Since we're doing segmentation the labels are image masks, i.e. the middle column of the image in the README file. These labels are stored in the labels folder.
The generator assumes that if the images and labels are sorted alphabetically then you can retrieve the image and corresponding mask by opening the files stored under the same index (i.e. images[i] corresponds to masks[i]). This is indeed a bit hacky, so feel free to rewrite the generator if it does not suit your needs.

**Comment by sreesindhu-sabbineni** [comment]
Thanks, I have one more question, what is the use of one_hot_label in generator. I didn't understand the purpose of it for mask labels. Can you please explain.

**Comment by Attila94** [comment]
If you mean `one_hot_it`: Keras uses [one-hot encoding](https://machinelearningmastery.com/how-to-one-hot-encode-sequence-data-in-python/).
